using System.ComponentModel.DataAnnotations;

namespace Lykke.Snow.Notifications.Client.Model.Requests
{
    /// <summary>
    /// Device registration request
    /// </summary>
    public class RegisterDeviceRequest
    {
        /// <summary>
        /// AccountId that will be associated with the device
        /// </summary>
        /// <value></value>
        [Required]
        public string AccountId { get; }

        /// <summary>
        /// FCM registration token
        /// </summary>
        /// <value></value>
        [Required]
        public string DeviceToken { get; }

        /// <summary>
        /// Unique device id that's been generated by the mobile client.
        /// </summary>
        /// <value></value>
        [Required]
        public string DeviceId { get; }

        /// <summary>
        /// The language for the device.
        /// </summary>
        /// <value></value>
        [Required]
        public string Locale { get; }
    }
}
